extends Node

signal signal_input_scheme_changed

signal signal_level_won
signal signal_level_reset
signal signal_level_advance
signal signal_level_jump_to(id:int)
signal signal_levels_finished

signal signal_check_win_condition

signal signal_daynight_mode_changed
signal signal_translation_locale_changed

signal signal_simu_event_left_clk
signal signal_simu_event_right_clk
